# Generated by Django 4.0.1 on 2022-02-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_comentario_usuario_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario_comentario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome_comentario',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
    ]
